
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yiwbtrwfyygzhhsjcaqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlpd2J0cndmeXlnemhoc2pjYXFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2Mjk4NDEsImV4cCI6MjA1ODIwNTg0MX0.120qLHBT6_pPVL3g6tNOesL3n_HL4py9lZVgqF1mg3I";

// Create a configured Supabase client with options
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true
    }
  }
);
